# This file will be included by the Makefile under the project directory.

FLOAT_OBJ := $(FLOAT:.a=.o)

$(FLOAT): $(FLOAT_OBJ)
	ar r $(FLOAT) $(FLOAT_OBJ)

# TODO: write a rule for generating $(FLOAT_OBJ)

FLOAT_FLAGS := -m32 -fno-builtin -I$(LIB_COMMON_DIR) -c

$(FLOAT_OBJ):
	$(call make_command,$(CC), $(FLOAT_FLAGS), FLOAT, lib-common/FLOAT.c)
